# Generated by Django 2.0.2 on 2018-03-02 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20180222_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilledOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_fulfilled', models.BooleanField()),
                ('date_time_fulfilled', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
