# Generated by Django 2.0.2 on 2018-03-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_fulfilledorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfilledorders',
            name='date_time_fulfilled',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
